#!/usr/bin/env bash
# Congure Nginx so that its HTTP response contains
# a custom header
#
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
   balance roundrobin
   server 486147-web-01 52.87.254.216 check
   server 486147-web-02 54.165.132.167 check
"
# update packages
apt-get -y update
apt-get -y upgrade

# Add HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balance" >> /etc/haproxy/haproxy.cfg
service haproxy restart
